[build]
  functions = "functions"
  command = "yarn run build"

[[redirects]]
  from = "/zoom-meeting-webhook-handler"
  to = "/.netlify/functions/zoom-meeting-webhook-handler"
  status = 200

[[redirects]]
  from = "/slack-interactivity"
  to = "/.netlify/functions/slack-interactivity"
  status = 200

[[redirects]]
  from = "/slack-events"
  to = "/.netlify/functions/slack-events"
  status = 200

[[redirects]]
  from = "/slack-send-message"
  to = "/.netlify/functions/slack-send-message-background"
  status = 200

[[redirects]]
  from = "/event-reminders"
  to = "/.netlify/functions/event-reminders-background"
  status = 200

[[redirects]]
  from = "/handle-participant-joined-left-background"
  to = "/.netlify/functions/handle-participant-joined-left-background"
  status = 200