[build]
  functions = "functions"

[[redirects]]
  from = "/zoom-meeting-webhook-handler"
  to = "/.netlify/functions/zoom-meeting-webhook-handler"
  status = 200

[[redirects]]
  from = "/slack-interactivity"
  to = "/.netlify/functions/slack-interactivity"
  status = 200