[build]
  functions = "functions"

[[redirects]]
  from = "/zoom-meeting-webhook-handler"
  to = "/.netlify/functions/zoom-meeting-webhook-handler"
  status = 200

[[redirects]]
  from = "/slack-interactivity"
  to = "/.netlify/functions/slack-interactivity"
  status = 200

[[redirects]]
  from = "/slack-events"
  to = "/.netlify/functions/slack-events"
  status = 200

[[redirects]]
  from = "/slack-send-message"
  to = "/.netlify/functions/slack-send-message-background"
  status = 200


[context.deploy-preview.environment]
SLACK_SIGNING_SECRET='e032ed822b88cbd223fe002ce027c0b5'
SLACK_BOT_TOKEN='xoxb-2058222876048-2047060586769-vbavfhv9iv0pYfyW93rfhnfX'